<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630120102 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE productos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, num_serie VARCHAR(255) NOT NULL, num_inventario VARCHAR(255) NOT NULL, coste_compra INT NOT NULL, anios_amortizar INT NOT NULL, fecha_compra DATE NOT NULL, prestar INT NOT NULL, descripcion TEXT NOT NULL, vida VARCHAR(255) NOT NULL, fecha_activacion DATE NOT NULL, valor INT NOT NULL, proveedor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_767490E6CB305D73 ON productos (proveedor_id)');
        $this->addSql('CREATE TABLE proveedores (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, nif VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE usuarios (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, log_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE productos ADD CONSTRAINT FK_767490E6CB305D73 FOREIGN KEY (proveedor_id) REFERENCES proveedores (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE product');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, num_serie VARCHAR(255) NOT NULL, num_inventario VARCHAR(255) NOT NULL, coste_compra INT NOT NULL, anios_amortizar INT NOT NULL, fecha_compra DATE NOT NULL, prestar INT NOT NULL, descripcion TEXT NOT NULL, vida VARCHAR(255) NOT NULL, fecha_activacion DATE NOT NULL, valor INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE productos DROP CONSTRAINT FK_767490E6CB305D73');
        $this->addSql('DROP TABLE productos');
        $this->addSql('DROP TABLE proveedores');
        $this->addSql('DROP TABLE usuarios');
    }
}
