<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630112901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, num_serie VARCHAR(255) NOT NULL, num_inventario VARCHAR(255) NOT NULL, coste_compra INT NOT NULL, anios_amortizar INT NOT NULL, fecha_compra DATE NOT NULL, prestar INT NOT NULL, descripcion TEXT NOT NULL, vida VARCHAR(255) NOT NULL, fecha_activacion DATE NOT NULL, valor INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE product');
    }
}
