<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630141711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorias (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, prestar INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, accion INT NOT NULL, datos TEXT NOT NULL, fecha DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE prestamos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, estado INT NOT NULL, motivo VARCHAR(255) NOT NULL, fecha_entrega DATE NOT NULL, dpto VARCHAR(255) NOT NULL, curso INT NOT NULL, motivoanular TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE prestamosproductos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE categorias');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE prestamos');
        $this->addSql('DROP TABLE prestamosproductos');
    }
}
